# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083663e9a956a39d13e43f72cb16cbab1ed8332eddd200b85ef46644a96f091c4736ec59acebe763e1bbe6c06bf15d010753946c03f207c64af0eb5c8b84cc4c

test:
  secret_key_base: f49bc7ef9006ea08eb08ccaedcb3890a346981deca84a38ae101a7211d9c481ab7156762a9aae8947f5691f1bb2bb622f044b173b512567fa752aeb9c612f876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
